spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter:
    create: All tasks

#Mailing
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: "camundauniversity@gmail.com"
spring.mail.password: temporaryPassword
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.socketFactory.port: 465
spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.starttls.enable: true

#Twitter
twitter.token: fsdafdsaffsdafsd435
twitter.tokenSecret: 46456ghfdhgfbgfd
twitter.apiKey: fsdafsfsda
twitter.apiKeySecret: fdsafsda
server:
  port: 8080
